import { Category, Dish, Review, Translation, ArrayTranslation } from './types';

export const HERO_IMAGE = '/src/assets/images/restaurant_hero_banner_1784588858619.jpg';

export const DISHES: Dish[] = [
  // --- BREAKFAST (Doručak) ---
  {
    id: 'brk_1',
    name: { sr: 'Kroasan čokolada', en: 'Chocolate Croissant', sq: 'Kroasant me Çokollatë' },
    description: { sr: 'Mekani lisnati kroasan sa lešnikom i čokoladnim kremom.', en: 'Warm croissant filled with chocolate cream and hazelnuts.', sq: 'Kroasant i shkrifët i mbushur me krem çokollate dhe lajthi.' },
    price: 2.00,
    category: Category.BREAKFAST,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500&auto=format&fit=crop&q=80',
    allergens: ['gluten', 'dairy', 'nuts'],
    dietary: ['veg'],
    calories: 340,
    prepTime: 5,
    featured: true,
    ingredients: { sr: ['Kroasan', 'Čokoladni krem', 'Lešnici'], en: ['Croissant', 'Chocolate cream', 'Hazelnuts'], sq: ['Kroasant', 'Krem çokollate', 'Lajthi'] }
  },
  {
    id: 'brk_2',
    name: { sr: 'Kroasan pistaći', en: 'Pistachio Croissant', sq: 'Kroasant me Pistaq' },
    description: { sr: 'Lisnati kroasan punjen prefinjenim kremom od pistaća.', en: 'Flaky croissant filled with rich pistachio cream.', sq: 'Kroasant i mbushur me krem të pasur pistaqi.' },
    price: 3.00,
    category: Category.BREAKFAST,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80',
    allergens: ['gluten', 'dairy', 'nuts'],
    dietary: ['veg'],
    calories: 360,
    prepTime: 5,
    featured: false,
    ingredients: { sr: ['Kroasan', 'Krem od pistaća', 'Pistaći'], en: ['Croissant', 'Pistachio cream', 'Pistachios'], sq: ['Kroasant', 'Krem pistaqi', 'Pistaqë'] }
  },
  {
    id: 'brk_3',
    name: { sr: 'Jaja na oko', en: 'Sunny-Side Up Eggs', sq: 'Vezë Sy' },
    description: { sr: 'Tri jaja na oko sa feta sirom, svežim paradajzom i maslinama (230g).', en: 'Three fresh eggs, local feta cheese, tomatoes, and olives.', sq: 'Tri vezë sy, djathë feta, domate dhe ullinj.' },
    price: 3.00,
    category: Category.BREAKFAST,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500&auto=format&fit=crop&q=80',
    allergens: ['egg', 'dairy'],
    dietary: ['veg', 'gf'],
    calories: 320,
    prepTime: 8,
    featured: false,
    ingredients: { sr: ['3 jaja', 'Feta sir', 'Paradajz', 'Masline'], en: ['3 eggs', 'Feta cheese', 'Tomato', 'Olives'], sq: ['3 vezë', 'Djathë feta', 'Domate', 'Ullinj'] }
  },
  {
    id: 'brk_4',
    name: { sr: 'Omlet / Kajgana po želji', en: 'Omelette / Scrambled Eggs', sq: 'Omëletë / Vezë të Rrahura' },
    description: { sr: 'Tri jaja, sir, povrće, goveđi pršut, mix zelenih salata i ajvar (300g).', en: 'Three eggs, cheese, veggies, beef prosciutto, greens, and ajvar.', sq: 'Tri vezë, djathë, perime, prshutë gjedhi, sallatë dhe ajvar.' },
    price: 5.00,
    category: Category.BREAKFAST,
    image: 'https://images.unsplash.com/photo-1494597564530-871f2b93ac55?w=500&auto=format&fit=crop&q=80',
    allergens: ['egg', 'dairy'],
    dietary: [],
    calories: 450,
    prepTime: 10,
    featured: true,
    ingredients: { sr: ['3 jaja', 'Goveđi pršut', 'Domaći sir', 'Domaći ajvar'], en: ['3 eggs', 'Beef prosciutto', 'Local cheese', 'House ajvar'], sq: ['3 vezë', 'Prshutë gjedhi', 'Djathë shtëpie', 'Ajvar shtëpie'] }
  },
  {
    id: 'brk_5',
    name: { sr: 'Gurmanski doručak', en: 'Gourmet Breakfast', sq: 'Mëngjes Gurman' },
    description: { sr: 'Dva jaja, juneća kobasica, domaći sir, pomfrit i aurora sos (320g).', en: 'Two eggs, beef sausage, local cheese, fries, and aurora sauce.', sq: 'Dy vezë, salsiçe gjedhi, djathë shtëpie, patate të skuqura dhe salcë aurora.' },
    price: 5.50,
    category: Category.BREAKFAST,
    image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=500&auto=format&fit=crop&q=80',
    allergens: ['egg', 'dairy', 'gluten'],
    dietary: [],
    calories: 680,
    prepTime: 12,
    featured: true,
    ingredients: { sr: ['2 jaja', 'Juneća kobasica', 'Domaći sir', 'Pomfrit', 'Aurora sos'], en: ['2 eggs', 'Beef sausage', 'Local cheese', 'French fries', 'Aurora sauce'], sq: ['2 vezë', 'Salsiçe gjedhi', 'Djathë shtëpie', 'Patate të skuqura', 'Salcë aurora'] }
  },

  // --- FOOD (Hrana) ---
  {
    id: 'fod_1',
    name: { sr: 'Selekcija sireva', en: 'Cheese Selection', sq: 'Përzgjedhje Djathrash' },
    description: { sr: 'Selekcija odabranih sireva: domaći, edamer, mocarela, gorgonzola, dimljeni.', en: 'Selected platter of local, Edam, mozzarella, gorgonzola, and smoked cheeses.', sq: 'Djathëra të përzgjedhur: shtëpie, edamer, mocarelë, gorgonxolë, i tymosur.' },
    price: 12.00,
    category: Category.FOOD,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=80',
    allergens: ['dairy'],
    dietary: ['veg', 'gf'],
    calories: 580,
    prepTime: 8,
    featured: true,
    ingredients: { sr: ['Domaći sir', 'Edamer', 'Mocarela', 'Gorgonzola', 'Dimljeni sir'], en: ['Local cheese', 'Edam', 'Mozzarella', 'Gorgonzola', 'Smoked cheese'], sq: ['Djathë shtëpie', 'Edamer', 'Mocarelë', 'Gorgonxolë', 'Djathë i tymosur'] }
  },
  {
    id: 'fod_2',
    name: { sr: 'Hamburger', en: 'Classic Hamburger', sq: 'Hamburger Klasik' },
    description: { sr: 'Sočan juneći burger (150g) poslužen u mekoj domaćoj lepinji.', en: 'Juicy 150g beef burger served inside a warm local lepinja bread.', sq: 'Hamburger i lëngshëm me mish gjedhi 150g në bukë të ngrohtë lepinja.' },
    price: 3.50,
    category: Category.FOOD,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=80',
    allergens: ['gluten'],
    dietary: [],
    calories: 520,
    prepTime: 12,
    featured: true,
    ingredients: { sr: ['Juneća pljeskavica', 'Lepinja', 'Salata', 'Prilozi'], en: ['Beef patty', 'Lepinja bread', 'Salad', 'Sauces'], sq: ['Qofte gjedhi', 'Bukë lepinja', 'Sallatë', 'Salca'] }
  },
  {
    id: 'fod_3',
    name: { sr: 'Pileći file u lepinji', en: 'Chicken Fillet in Lepinja', sq: 'File Pule në Lepinja' },
    description: { sr: 'Grilovani pileći file (200g) u domaćoj lepinji sa salatama.', en: 'Grilled chicken breast (200g) in a fresh lepinja bread with salads.', sq: 'File pule në skarë (200g) në bukë lepinja shtëpie me sallatë.' },
    price: 5.00,
    category: Category.FOOD,
    image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=500&auto=format&fit=crop&q=80',
    allergens: ['gluten'],
    dietary: [],
    calories: 460,
    prepTime: 10,
    featured: false,
    ingredients: { sr: ['Pileći file', 'Domaća lepinja', 'Salate'], en: ['Chicken breast', 'Lepinja bread', 'Salads'], sq: ['File pule', 'Bukë lepinja', 'Sallatë'] }
  },
  {
    id: 'fod_4',
    name: { sr: 'Gurmanska u lepinji', en: 'Gourmet Patty in Lepinja', sq: 'Gurmane në Lepinja' },
    description: { sr: 'Pljeskavica punjena sirom i začinima (250g) u toploj lepinji.', en: 'Spiced beef patty (250g) stuffed with cheese inside a warm lepinja.', sq: 'Pleskavicë gurmane e mbushur me djathë (250g) në bukë të ngrohtë.' },
    price: 5.00,
    category: Category.FOOD,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop&q=80',
    allergens: ['gluten', 'dairy'],
    dietary: ['spicy'],
    calories: 640,
    prepTime: 12,
    featured: true,
    ingredients: { sr: ['Gurmansko meso', 'Sir', 'Lepinja'], en: ['Gourmet meat', 'Cheese', 'Lepinja bread'], sq: ['Mish gurman', 'Djathë', 'Bukë lepinja'] }
  },
  {
    id: 'fod_5',
    name: { sr: 'Pileći file (tanjir)', en: 'Grilled Chicken Platter', sq: 'File Pule (Pjatë)' },
    description: { sr: 'Pileći fileti (350g) sa pomfritom, miksom zelenih salata i aurora sosom.', en: 'Grilled chicken (350g) with fries, mixed salad, and aurora sauce.', sq: 'File pule në skarë (350g) me patate të skuqura, sallatë dhe salcë aurora.' },
    price: 9.00,
    category: Category.FOOD,
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=500&auto=format&fit=crop&q=80',
    allergens: ['dairy'],
    dietary: [],
    calories: 590,
    prepTime: 15,
    featured: false,
    ingredients: { sr: ['Piletina', 'Pomfrit', 'Miks salata', 'Aurora sos'], en: ['Chicken', 'French fries', 'Mixed salad', 'Aurora sauce'], sq: ['Mish pule', 'Patate të skuqura', 'Sallatë', 'Salcë aurora'] }
  },
  {
    id: 'fod_6',
    name: { sr: 'Gurmanska pljeskavica (tanjir)', en: 'Gourmet Patty Platter', sq: 'Pljeskavicë Gurmane (Pjatë)' },
    description: { sr: 'Pljeskavica sa sirom (400g), kajmakom, pekarskim krompirom i lepinjom.', en: 'Beef patty (400g) with cheese, kajmak, roasted potatoes, and lepinja.', sq: 'Pleskavicë me djathë (400g), kajmak, patate furre dhe lepinja.' },
    price: 10.00,
    category: Category.FOOD,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop&q=80',
    allergens: ['gluten', 'dairy'],
    dietary: ['spicy'],
    calories: 890,
    prepTime: 18,
    featured: true,
    ingredients: { sr: ['Juneće meso', 'Kajmak', 'Krompir', 'Lepinja'], en: ['Beef patty', 'Kajmak cream', 'Potatoes', 'Lepinja bread'], sq: ['Mish gjedhi', 'Kajmak', 'Patate', 'Bukë lepinja'] }
  },
  {
    id: 'fod_7',
    name: { sr: 'Ćevapi', en: 'Traditional Cevapi', sq: 'Qebapë Tradicionalë' },
    description: { sr: 'Domaći ćevapi u lepinji sa crnim lukom i pomfritom.', en: 'Balkan beef cevapi inside warm lepinja with onions and fries.', sq: 'Qebapë shtëpie të lëngshëm të shërbyer në lepinja me qepë dhe patate.' },
    price: 7.00,
    category: Category.FOOD,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=80',
    allergens: ['gluten'],
    dietary: [],
    calories: 690,
    prepTime: 12,
    featured: true,
    ingredients: { sr: ['Ćevapi', 'Lepinja', 'Luk', 'Pomfrit'], en: ['Cevapi', 'Lepinja bread', 'Onions', 'French fries'], sq: ['Qebapë', 'Bukë lepinja', 'Qepë', 'Patate'] }
  },

  // --- HOT DRINKS (Kafa & Topli napici) ---
  {
    id: 'drk_espresso',
    name: { sr: 'Espresso 0.03l', en: 'Espresso 0.03l', sq: 'Espresso 0.03l' },
    description: { sr: 'Klasični espresso punog i bogatog ukusa.', en: 'Classic rich espresso.', sq: 'Ekspres kafe klasike me aromë të pasur.' },
    price: 1.30,
    category: Category.HOT_DRINKS,
    image: '',
    allergens: [],
    dietary: [],
    calories: 2,
    prepTime: 2,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_macchiato',
    name: { sr: 'Macchiato 0.05l', en: 'Macchiato 0.05l', sq: 'Macchiato 0.05l' },
    description: { sr: 'Espresso sa kapljicom tople mlečne pene.', en: 'Espresso with a dash of warm milk foam.', sq: 'Makiato klasike me pak qumësht.' },
    price: 1.40,
    category: Category.HOT_DRINKS,
    image: '',
    allergens: ['dairy'],
    dietary: [],
    calories: 15,
    prepTime: 2,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_veliki_macchiato',
    name: { sr: 'Veliki macchiato 0.15l', en: 'Large Macchiato 0.15l', sq: 'Makiato e Madhe 0.15l' },
    description: { sr: 'Dupli espresso sa bogatom mlečnom penom.', en: 'Double shot of espresso with generous frothed milk.', sq: 'Makiato e madhe me shkumë të bollshme qumështi.' },
    price: 1.90,
    category: Category.HOT_DRINKS,
    image: '',
    allergens: ['dairy'],
    dietary: [],
    calories: 45,
    prepTime: 2,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_capuccino',
    name: { sr: 'Capuccino 0.15l', en: 'Cappuccino 0.15l', sq: 'Kapuçino 0.15l' },
    description: { sr: 'Tradicionalni italijanski kapućino sa kremastom penom.', en: 'Traditional Italian cappuccino with creamy milk foam.', sq: 'Kapuçino me shkumë krem me qumësht.' },
    price: 2.00,
    category: Category.HOT_DRINKS,
    image: '',
    allergens: ['dairy'],
    dietary: [],
    calories: 80,
    prepTime: 2,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_ness_cafe',
    name: { sr: 'Ness cafe 0.25l', en: 'Nescafe 0.25l', sq: 'Neskafe 0.25l' },
    description: { sr: 'Umutiti instant kafu po vašem izboru sa mlekom.', en: 'Creamy whipped instant coffee with milk.', sq: 'Kafe çastit e rrahur me qumësht.' },
    price: 2.00,
    category: Category.HOT_DRINKS,
    image: '',
    allergens: ['dairy'],
    dietary: [],
    calories: 110,
    prepTime: 3,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_americano',
    name: { sr: 'Americano 0.15l', en: 'Americano 0.15l', sq: 'Americano 0.15l' },
    description: { sr: 'Produženi espresso sa toplom vodom.', en: 'Espresso shot diluted with hot water.', sq: 'Ekspres kafe e zgjatur me ujë të ngrohtë.' },
    price: 1.50,
    category: Category.HOT_DRINKS,
    image: '',
    allergens: [],
    dietary: [],
    calories: 5,
    prepTime: 2,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_kuvana_kafa',
    name: { sr: 'Kuvana kafa 0.15l', en: 'Turkish Coffee 0.15l', sq: 'Kafë Turke 0.15l' },
    description: { sr: 'Domaća tradicionalna kuvana kafa.', en: 'Traditional homemade Turkish coffee.', sq: 'Kafë shtëpie e gatuar sipas traditës.' },
    price: 1.30,
    category: Category.HOT_DRINKS,
    image: '',
    allergens: [],
    dietary: [],
    calories: 2,
    prepTime: 3,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_baileys_coffee',
    name: { sr: 'Baileys coffe 0.25l', en: 'Baileys Coffee 0.25l', sq: 'Kafe Baileys 0.25l' },
    description: { sr: 'Kafa sa kremastim Baileys likerom.', en: 'Hot coffee combined with smooth Baileys liqueur.', sq: 'Kafe e ngrohtë me liker krem Baileys.' },
    price: 3.90,
    category: Category.HOT_DRINKS,
    image: '',
    allergens: ['dairy'],
    dietary: [],
    calories: 180,
    prepTime: 3,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_caffe_latte',
    name: { sr: 'Caffe latte 0.25l', en: 'Caffe Latte 0.25l', sq: 'Kafe Late 0.25l' },
    description: { sr: 'Espresso sa dosta toplog mleka i malo pjene.', en: 'Espresso with plenty of warm milk and light foam.', sq: 'Ekspres kafe me qumësht të ngrohtë dhe pak shkumë.' },
    price: 2.50,
    category: Category.HOT_DRINKS,
    image: '',
    allergens: ['dairy'],
    dietary: [],
    calories: 120,
    prepTime: 2,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_pistachio_latte',
    name: { sr: 'Pistachio latte 0.15l', en: 'Pistachio Latte 0.15l', sq: 'Late me Pistaq 0.15l' },
    description: { sr: 'Latte kafa sa prefinjenim i slatkim sirupom od pistaća.', en: 'Latte infused with high-quality sweet pistachio syrup.', sq: 'Kafe late e pasur me shurup pistaqi.' },
    price: 3.80,
    category: Category.HOT_DRINKS,
    image: '',
    allergens: ['dairy', 'nuts'],
    dietary: [],
    calories: 190,
    prepTime: 3,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_affogato',
    name: { sr: 'Affogato 0.05l', en: 'Affogato 0.05l', sq: 'Afogato 0.05l' },
    description: { sr: 'Kugla sladoleda od vanile "prelivena" espresso kafom.', en: 'Vanilla ice cream drowned in a hot shot of espresso.', sq: 'Një top akullore vanilje e mbytur në kafe ekspres.' },
    price: 2.80,
    category: Category.HOT_DRINKS,
    image: '',
    allergens: ['dairy'],
    dietary: [],
    calories: 140,
    prepTime: 2,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_topla_cokolada',
    name: { sr: 'Topla čokolada 0.25l', en: 'Hot Chocolate 0.25l', sq: 'Çokollatë e Ngrohtë 0.25l' },
    description: { sr: 'Gusta i kremasta topla čokolada.', en: 'Thick and creamy warm hot chocolate.', sq: 'Çokollatë e ngrohtë e trashë i kremoze.' },
    price: 3.00,
    category: Category.HOT_DRINKS,
    image: '',
    allergens: ['dairy'],
    dietary: [],
    calories: 220,
    prepTime: 3,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_kakao',
    name: { sr: 'Kakao 0.25l', en: 'Cocoa 0.25l', sq: 'Kakao 0.25l' },
    description: { sr: 'Topli hranljivi napitak od kakaa sa mlekom.', en: 'Warm nutritious cocoa with milk.', sq: 'Pije e ngrohtë ushqyese kakao me qumësht.' },
    price: 2.00,
    category: Category.HOT_DRINKS,
    image: '',
    allergens: ['dairy'],
    dietary: [],
    calories: 160,
    prepTime: 2,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_caj',
    name: { sr: 'Čaj 0.20l', en: 'Tea 0.20l', sq: 'Çaj 0.20l' },
    description: { sr: 'Selekcija premium čajeva po vašem izboru sa limunom i medom.', en: 'Selection of premium teas served with lemon and honey.', sq: 'Përzgjedhje čajrash premium të shërbyera me limon dhe mjaltë.' },
    price: 1.50,
    category: Category.HOT_DRINKS,
    image: '',
    allergens: [],
    dietary: [],
    calories: 10,
    prepTime: 3,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },

  // --- NON ALCOHOLIC (Bezalkoholna pića i vode) ---
  {
    id: 'drk_voda_negazirana',
    name: { sr: 'Negazirana voda 0.33l', en: 'Still Water 0.33l', sq: 'Ujë pa Gaz 0.33l' },
    description: { sr: 'Prirodna izvorska negazirana voda.', en: 'Refreshing natural spring still water.', sq: 'Ujë burimi natyral pa gaz.' },
    price: 1.50,
    category: Category.NON_ALCOHOLIC,
    image: '',
    allergens: [],
    dietary: [],
    calories: 0,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_voda_gazirana',
    name: { sr: 'Gazirana voda 0.25l', en: 'Sparkling Water 0.25l', sq: 'Ujë me Gaz 0.25l' },
    description: { sr: 'Gazirana mineralna izvorska voda.', en: 'Refreshing mineral sparkling water.', sq: 'Ujë mineral i gazuar.' },
    price: 1.50,
    category: Category.NON_ALCOHOLIC,
    image: '',
    allergens: [],
    dietary: [],
    calories: 0,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_sok_gazirani',
    name: { sr: 'Gazirani sokovi 0.25l', en: 'Sodas 0.25l', sq: 'Sok me Gaz 0.25l' },
    description: { sr: 'Coca-Cola, Fanta, Sprite, Cocta...', en: 'Selection of popular carbonated soft drinks.', sq: 'Përzgjedhje pijesh popullore me gaz.' },
    price: 2.50,
    category: Category.NON_ALCOHOLIC,
    image: '',
    allergens: [],
    dietary: [],
    calories: 140,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_sok_negazirani',
    name: { sr: 'Negazirani sokovi 0.20l', en: 'Juices 0.20l', sq: 'Sok pa Gaz 0.20l' },
    description: { sr: 'Narandža, jabuka, jagoda, breskva...', en: 'Selection of premium non-carbonated fruit juices.', sq: 'Përzgjedhje lëngjesh frutash pa gaz.' },
    price: 2.50,
    category: Category.NON_ALCOHOLIC,
    image: '',
    allergens: [],
    dietary: [],
    calories: 110,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_orangina',
    name: { sr: 'Orangina 0.25l', en: 'Orangina 0.25l', sq: 'Orangina 0.25l' },
    description: { sr: 'Osvežavajući blago gazirani napitak sa pulpom narandže.', en: 'Refreshing lightly sparkling citrus beverage with orange pulp.', sq: 'Pije e freskët me gaz dhe me tulin e portokallit.' },
    price: 3.00,
    category: Category.NON_ALCOHOLIC,
    image: '',
    allergens: [],
    dietary: [],
    calories: 120,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_cedevita',
    name: { sr: 'Cedevita 0.33l', en: 'Cedevita 0.33l', sq: 'Cedevita 0.33l' },
    description: { sr: 'Šumeći vitaminski instant napitak.', en: 'Instant multivitamin drink of your choice.', sq: 'Pije multivitaminike e çastit.' },
    price: 2.00,
    category: Category.NON_ALCOHOLIC,
    image: '',
    allergens: [],
    dietary: [],
    calories: 70,
    prepTime: 2,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_ice_tea',
    name: { sr: 'Ice Tea 0.20l', en: 'Ice Tea 0.20l', sq: 'Çaj i Ftohtë 0.20l' },
    description: { sr: 'Osvežavajući hladni čaj od breskve ili šumskog voća.', en: 'Refreshing cold iced tea (peach or forest fruit).', sq: 'Çaj i ftohtë freskues me shije pjeshke ose frutash pylli.' },
    price: 2.00,
    category: Category.NON_ALCOHOLIC,
    image: '',
    allergens: [],
    dietary: [],
    calories: 80,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_red_bull',
    name: { sr: 'Red bull 0.25l', en: 'Red Bull 0.25l', sq: 'Red Bull 0.25l' },
    description: { sr: 'Popularni energetski napitak.', en: 'Popular premium energy drink.', sq: 'Pije e njohur energjike.' },
    price: 4.00,
    category: Category.NON_ALCOHOLIC,
    image: '',
    allergens: [],
    dietary: [],
    calories: 115,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_limunada',
    name: { sr: 'Limunada 0.3l', en: 'Fresh Lemonade 0.3l', sq: 'Limonadë e Freskët 0.3l' },
    description: { sr: 'Sveže ceđeni sok od prirodnog limuna sa ledom.', en: 'Freshly squeezed lemon juice served cold.', sq: 'Lëng limoni i shtrydhur i freskët me akull.' },
    price: 2.50,
    category: Category.NON_ALCOHOLIC,
    image: '',
    allergens: [],
    dietary: [],
    calories: 45,
    prepTime: 2,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_cijeđena_pomorandža',
    name: { sr: 'Cijeđena pomorandža 0.3l', en: 'Fresh Squeezed Orange 0.3l', sq: 'Portokall i Shtrydhur 0.3l' },
    description: { sr: 'Sveže ceđeni 100% prirodni sok od pomorandže.', en: '100% fresh natural squeezed orange juice.', sq: 'Lëng portokalli i shtrydhur i freskët 100% natyral.' },
    price: 3.00,
    category: Category.NON_ALCOHOLIC,
    image: '',
    allergens: [],
    dietary: [],
    calories: 110,
    prepTime: 2,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },

  // --- ALCOHOL (Alkoholna pića, Aperitivi, Rakije, Vina, Piva) ---
  {
    id: 'drk_ramazzotti',
    name: { sr: 'Amaro Ramazzotti 0.03l', en: 'Amaro Ramazzotti 0.03l', sq: 'Amaro Ramazzotti 0.03l' },
    description: { sr: 'Tradicionalni italijanski digestiv bogatog ukusa.', en: 'Classic Italian herbal digestif.', sq: 'Liker bimor klasik italian digestiv.' },
    price: 3.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 80,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_amaro_montenegro',
    name: { sr: 'Amaro Montenegro 0.03l', en: 'Amaro Montenegro 0.03l', sq: 'Amaro Montenegro 0.03l' },
    description: { sr: 'Čuveni italijanski biljni liker od 40 lekovitih biljaka.', en: 'Famous Italian herbal liqueur made with 40 botanicals.', sq: 'Liker i njohur bimor italian me 40 bimë mjekësore.' },
    price: 3.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 90,
    prepTime: 1,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_gorki_list',
    name: { sr: 'Gorki list 0.03l', en: 'Gorki List 0.03l', sq: 'Gorki List 0.03l' },
    description: { sr: 'Gorki biljni liker na bazi pelina.', en: 'Traditional bitter wormwood herbal digestif liqueur.', sq: 'Liker i njohur i hidhur bimor i pelinit.' },
    price: 2.50,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 85,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_jagermeister',
    name: { sr: 'Jagermeister 0.03l', en: 'Jagermeister 0.03l', sq: 'Jagermeister 0.03l' },
    description: { sr: 'Ukusni biljni liker od 56 vrsta bilja.', en: 'Popular German herbal liqueur crafted from 56 botanicals.', sq: 'Liker i njohur gjerman bimor i bërë nga 56 bimë.' },
    price: 3.50,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 100,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_campari',
    name: { sr: 'Campari 0.03l', en: 'Campari 0.03l', sq: 'Campari 0.03l' },
    description: { sr: 'Prepoznatljivi italijanski gorko-slatki crveni aperitiv.', en: 'Famous bittersweet vibrant red Italian aperitif.', sq: 'Aperitivi i njohur i hidhur-ëmbël klasik italian me ngjyrë të kuqe.' },
    price: 3.50,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 80,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_amaretto',
    name: { sr: 'Amaretto 0.03l', en: 'Amaretto 0.03l', sq: 'Amaretto 0.03l' },
    description: { sr: 'Sladak liker sa prefinjenom aromom badema.', en: 'Sweet Italian liqueur with rich almond notes.', sq: 'Liker i ëmbël italian me aromë të pasur bajame.' },
    price: 3.50,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 110,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_pelinkovac',
    name: { sr: 'Pelinkovac 0.03l', en: 'Pelinkovac 0.03l', sq: 'Pelinkovac 0.03l' },
    description: { sr: 'Tradicionalni gorki biljni liker od pelina.', en: 'Traditional bitter wormwood digestif.', sq: 'Liker tradicional i hidhur me pelin.' },
    price: 2.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 75,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_baileys',
    name: { sr: 'Baileys 0.03l', en: 'Baileys 0.03l', sq: 'Baileys 0.03l' },
    description: { sr: 'Originalni irski kremasti liker sa notom kakaa i viskija.', en: 'Smooth original Irish cream liqueur.', sq: 'Liker krem i njohur irlandez me çokollatë.' },
    price: 3.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: ['dairy'],
    dietary: [],
    calories: 105,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_loza_kruna',
    name: { sr: 'Loza Kruna 0.03l', en: 'Grape Brandy Kruna 0.03l', sq: 'Raki Rrushi Kruna 0.03l' },
    description: { sr: 'Vrhunska crnogorska rakija od grožđa.', en: 'Premium Montenegrin double-distilled grape brandy.', sq: 'Raki rrushi premium e distiluar e Malit të Zi.' },
    price: 2.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 75,
    prepTime: 1,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_zuta_dunja',
    name: { sr: 'Žuta dunja 0.03l', en: 'Quince Brandy 0.03l', sq: 'Raki Ftoi 0.03l' },
    description: { sr: 'Kvalitetna rakija od dunje prefinjenog i toplog ukusa.', en: 'Premium quality aromatic quince fruit brandy.', sq: 'Raki ftoi premium mjaft aromatike i e ngrohtë.' },
    price: 3.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 75,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_zuta_viljamovka',
    name: { sr: 'Žuta Viljamovka 0.03l', en: 'Pear Brandy Viljamovka 0.03l', sq: 'Raki Dardhe Viljamovka 0.03l' },
    description: { sr: 'Ukusna rakija od kruške Viljamovke punog mirisa.', en: 'Williams pear brandy with an intense and rich aroma.', sq: 'Raki dardhe me shije mjaft të pasur Viljamovka.' },
    price: 3.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 78,
    prepTime: 1,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_sljiva_desetka',
    name: { sr: 'Šljiva desetka 0.03l', en: 'Plum Brandy Desetka 0.03l', sq: 'Raki Kumbulle Desetka 0.03l' },
    description: { sr: 'Kvalitetna rakija od šljive, odležala i punog ukusa.', en: 'Aged premium plum brandy with robust rich flavors.', sq: 'Raki kumbulle e vjetëruar me shije të plotë e të fortë.' },
    price: 3.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 75,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_medovaca',
    name: { sr: 'Medovača (Pevac) 0.03l', en: 'Honey Brandy (Pevac) 0.03l', sq: 'Raki Mjalti (Pevac) 0.03l' },
    description: { sr: 'Tradicionalna rakija sa dodatkom prirodnog meda.', en: 'Traditional brandy sweetened with natural organic honey.', sq: 'Raki e ëmbëlsuar me mjaltë natyral.' },
    price: 2.50,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 85,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_absolut_vodka',
    name: { sr: 'Absolut vodka 0.03l', en: 'Absolut Vodka 0.03l', sq: 'Absolut Vodka 0.03l' },
    description: { sr: 'Čista premium švedska votka.', en: 'Premium Swedish vodka.', sq: 'Vodka premium suedeze.' },
    price: 3.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 70,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_gin',
    name: { sr: 'Gin 0.03l', en: 'Gin 0.03l', sq: 'Xhin 0.03l' },
    description: { sr: 'Visokokvalitetni suvi džin od kleke.', en: 'Premium dry gin crafted with botanical juniper.', sq: 'Xhin premium i aromatizuar me dëllinjë.' },
    price: 3.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 75,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_tekila',
    name: { sr: 'Tekila 0.03l', en: 'Tequila 0.03l', sq: 'Tekila 0.03l' },
    description: { sr: 'Meksička tekila od plave agave.', en: 'Authentic Mexican tequila made with blue agave.', sq: 'Tekila origjinale meksikane e bërë nga agava e kaltër.' },
    price: 3.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 70,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_rum',
    name: { sr: 'Rum 0.03l', en: 'Rum 0.03l', sq: 'Rum 0.03l' },
    description: { sr: 'Odličan rum sa Kariba.', en: 'Quality rich Caribbean rum.', sq: 'Rum i shijshëm i Karaibeve.' },
    price: 3.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 75,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_martini_rosso',
    name: { sr: 'Martini rosso 0.05l', en: 'Martini Rosso 0.05l', sq: 'Martini Rosso 0.05l' },
    description: { sr: 'Slatki crveni italijanski vermut.', en: 'Sweet Italian red vermouth.', sq: 'Verë vermut i ëmbël i kuq italian.' },
    price: 3.50,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 80,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_martini_bianco',
    name: { sr: 'Martini bianco 0.05l', en: 'Martini Bianco 0.05l', sq: 'Martini Bianco 0.05l' },
    description: { sr: 'Beli slatki i aromatični vermut.', en: 'Sweet white aromatic vermouth.', sq: 'Verë vermut i ëmbël i aromatik i bardhë.' },
    price: 3.50,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 80,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_chivas_12',
    name: { sr: 'Chivas 12 y.o. 0.03l', en: 'Chivas 12 y.o. 0.03l', sq: 'Chivas 12 vjeçar 0.03l' },
    description: { sr: 'Premium blend škotski viski odležao 12 godina.', en: 'Premium blended Scotch whiskey aged 12 years.', sq: 'Uiski premium skocez i vjetëruar 12 vjet.' },
    price: 5.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 75,
    prepTime: 1,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_jack_daniels',
    name: { sr: 'Jack Daniels 0.03l', en: 'Jack Daniels 0.03l', sq: 'Jack Daniels 0.03l' },
    description: { sr: 'Legendarni američki Tenesi viski pročišćen kroz javorov ugalj.', en: 'Famous charcoal-mellowed Tennessee whiskey.', sq: 'Uiski i famshëm amerikan nga Tenesi.' },
    price: 4.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 75,
    prepTime: 1,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_johnnie_red',
    name: { sr: 'Johnnie Walker Red 0.03l', en: 'Johnnie Walker Red 0.03l', sq: 'Johnnie Walker Red 0.03l' },
    description: { sr: 'Najprodavaniji škotski viski na svetu, dinamičnog ukusa.', en: 'Best-selling blended Scotch whiskey in the world.', sq: 'Uiski i famshëm skocez i përzier me shije mjaft dinamike.' },
    price: 3.50,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 75,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_black_label',
    name: { sr: 'Black Label 0.03l', en: 'Black Label 0.03l', sq: 'Black Label 0.03l' },
    description: { sr: 'Luksuzni škotski viski, bogat i dimljen, odležao 12 godina.', en: 'Iconic luxurious rich and smoky Scotch whiskey.', sq: 'Uiski premium luksoz skocez i vjetëruar 12 vjet me shije pak si tym.' },
    price: 5.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 75,
    prepTime: 1,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_jameson',
    name: { sr: 'Jameson 0.03l', en: 'Jameson 0.03l', sq: 'Jameson 0.03l' },
    description: { sr: 'Trostruko distilovani glatki irski viski.', en: 'Triple-distilled, exceptionally smooth Irish whiskey.', sq: 'Uiski irlandez i distiluar tre herë mjaft i butë.' },
    price: 3.50,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 75,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_hennessy_vs',
    name: { sr: 'Hennessy V.S. 0.03l', en: 'Hennessy V.S. 0.03l', sq: 'Hennessy V.S. 0.03l' },
    description: { sr: 'Vrhunski francuski konjak prefinjene arome voća i hrasta.', en: 'Premium French cognac with rich toasted oak and fruit notes.', sq: 'Konjak premium francez me aromë lisi i frutash.' },
    price: 6.00,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 75,
    prepTime: 1,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_una',
    name: { sr: 'Una 0.15l', en: 'Una 0.15l', sq: 'Una 0.15l' },
    description: { sr: 'Premium lokalno alkoholno piće / liker.', en: 'Premium local drink / liqueur of unique recipe.', sq: 'Liker i pije premium lokale me recetë unike.' },
    price: 3.50,
    category: Category.ALCOHOL,
    image: '',
    allergens: [],
    dietary: [],
    calories: 120,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_niksicko',
    name: { sr: 'Nikšićko 0.33l', en: 'Niksicko Beer 0.33l', sq: 'Birrë Nikshiq 0.33l' },
    description: { sr: 'Legendarno svetlo lager pivo prepoznatljivog ukusa.', en: 'Traditional and legendary Montenegrin lager beer.', sq: 'Birra klasike e hapur tradicionale e Malit të Zi.' },
    price: 2.50,
    category: Category.BEERS,
    image: '',
    allergens: ['gluten'],
    dietary: [],
    calories: 140,
    prepTime: 1,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_stella',
    name: { sr: 'Stella Artois 0.33l', en: 'Stella Artois 0.33l', sq: 'Stella Artois 0.33l' },
    description: { sr: 'Premium belgijsko svetlo pivo prefinjenog ukusa.', en: 'Premium Belgian lager beer with a crisp and clean finish.', sq: 'Birrë lager premium belge me shije të pastër.' },
    price: 3.00,
    category: Category.BEERS,
    image: '',
    allergens: ['gluten'],
    dietary: [],
    calories: 145,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_bavaria',
    name: { sr: 'Bavaria 0.25l', en: 'Bavaria 0.25l', sq: 'Bavaria 0.25l' },
    description: { sr: 'Popularno holandsko svetlo lager pivo.', en: 'Popular refreshing Dutch lager beer.', sq: 'Birrë lager e hapur holandeze mjaft freskuese.' },
    price: 2.50,
    category: Category.BEERS,
    image: '',
    allergens: ['gluten'],
    dietary: [],
    calories: 110,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_corona',
    name: { sr: 'Corona 0.33l', en: 'Corona 0.33l', sq: 'Birrë Korona 0.33l' },
    description: { sr: 'Meksičko svetlo pivo, posluženo sa kriškom limete.', en: 'Famous Mexican light lager served with a slice of fresh lime.', sq: 'Birrë e hapur e famshme meksikane e shërbyer me limon jeshil.' },
    price: 4.00,
    category: Category.BEERS,
    image: '',
    allergens: ['gluten'],
    dietary: [],
    calories: 148,
    prepTime: 1,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_tuborg',
    name: { sr: 'Tuborg 0.33l', en: 'Tuborg 0.33l', sq: 'Birrë Tuborg 0.33l' },
    description: { sr: 'Osvežavajuće dansko svetlo lager pivo.', en: 'Refreshing light Danish lager beer.', sq: 'Birrë lager daneze mjaft freskuese.' },
    price: 2.50,
    category: Category.BEERS,
    image: '',
    allergens: ['gluten'],
    dietary: [],
    calories: 135,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_heineken',
    name: { sr: 'Heineken 0.25l', en: 'Heineken 0.25l', sq: 'Birrë Heineken 0.25l' },
    description: { sr: 'Svetski poznato holandsko premium svetlo pivo.', en: 'World-famous premium Dutch lager beer.', sq: 'Birrë lager premium e njohur holandeze.' },
    price: 3.50,
    category: Category.BEERS,
    image: '',
    allergens: ['gluten'],
    dietary: [],
    calories: 110,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_aspall_jabuka',
    name: { sr: 'Aspall Jabuka 0.33l', en: 'Aspall Apple Cider 0.33l', sq: 'Cider Aspall Mollë 0.33l' },
    description: { sr: 'Premium engleski cider od jabuke prefinjene arome.', en: 'Premium English apple cider with deep fruit character.', sq: 'Cider premium anglez me mollë mjaft aromatike.' },
    price: 3.00,
    category: Category.BEERS,
    image: '',
    allergens: [],
    dietary: [],
    calories: 140,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_aspall_malina',
    name: { sr: 'Aspall Malina 0.33l', en: 'Aspall Raspberry Cider 0.33l', sq: 'Cider Aspall Manaferrë 0.33l' },
    description: { sr: 'Premium engleski cider od jabuke sa dodatkom maline.', en: 'Premium English cider infused with refreshing raspberry.', sq: 'Cider premium anglez me mollë i mjedër freskuese.' },
    price: 3.00,
    category: Category.BEERS,
    image: '',
    allergens: [],
    dietary: [],
    calories: 145,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_spricer',
    name: { sr: 'Špricer 0.25l', en: 'Spritzer 0.25l', sq: 'Shpricer 0.25l' },
    description: { sr: 'Tradicionalna mešavina belog vina i gazirane vode.', en: 'Traditional refreshing mix of white wine and sparkling water.', sq: 'Përzierje tradicionale e verës së bardhë me ujë me gaz.' },
    price: 3.50,
    category: Category.WINES,
    image: '',
    allergens: [],
    dietary: [],
    calories: 90,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_chardonnay_plantaze',
    name: { sr: 'Chardonnay Plantaže 0.187l', en: 'Chardonnay Plantaze 0.187l', sq: 'Chardonnay Plantaze 0.187l' },
    description: { sr: 'Kvalitetno crnogorsko belo vino, sveže i lagano.', en: 'Quality Montenegrin dry white wine, fresh and citrusy.', sq: 'Verë e bardhë cilësore e Malit të Zi, e freskët i me shije agrumesh.' },
    price: 4.00,
    category: Category.WINES,
    image: '',
    allergens: [],
    dietary: [],
    calories: 130,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_vranac_plantaze',
    name: { sr: 'Vranac Plantaže pr. 0.187l', en: 'Vranac Plantaze Premium 0.187l', sq: 'Vranac Plantaze Premium 0.187l' },
    description: { sr: 'Vrhunsko crnogorsko suvo crveno vino punog ukusa.', en: 'Premium dry red wine of Montenegro with rich berry notes.', sq: 'Verë e kuqe e thatë premium e Malit të Zi.' },
    price: 4.00,
    category: Category.WINES,
    image: '',
    allergens: [],
    dietary: [],
    calories: 135,
    prepTime: 1,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_roze_plantaze_small',
    name: { sr: 'Roze Plantaže 0.187l', en: 'Rose Plantaze 0.187l', sq: 'Rozë Plantaze 0.187l' },
    description: { sr: 'Sveže i voćno roze vino izuzetnog kvaliteta.', en: 'Fresh and fruity rose wine of high quality.', sq: 'Verë rozë e freskët i frutash me cilësi të lartë.' },
    price: 4.00,
    category: Category.WINES,
    image: '',
    allergens: [],
    dietary: [],
    calories: 125,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_grasevina',
    name: { sr: 'Graševina Kutjevo 0.187l', en: 'Grasevina Kutjevo 0.187l', sq: 'Verë Grasevina Kutjevo 0.187l' },
    description: { sr: 'Ukusno, pitko i elegantno belo vino iz Kutjeva.', en: 'Elegant, delicious and crisp white wine from Kutjevo.', sq: 'Verë e bardhë elegante, e shijshme i e freskët nga Kutjevo.' },
    price: 5.00,
    category: Category.WINES,
    image: '',
    allergens: [],
    dietary: [],
    calories: 130,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_cabernet_plantaze',
    name: { sr: 'Cabernet Plantaže 0.70l', en: 'Cabernet Plantaze 0.70l', sq: 'Kabernet Plantaze 0.70l' },
    description: { sr: 'Vrhunsko crveno vino, bogate strukture i punog ukusa.', en: 'Premium red wine with a rich structure and bold body.', sq: 'Verë e kuqe premium me strukturë të pasur i shije të plotë.' },
    price: 20.00,
    category: Category.WINES,
    image: '',
    allergens: [],
    dietary: [],
    calories: 520,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_malvazija_plantaze',
    name: { sr: 'Malvazija Plantaže 0.70l', en: 'Malvazija Plantaze 0.70l', sq: 'Malvazia Plantaze 0.70l' },
    description: { sr: 'Vrhunsko belo vino izuzetne svežine i cvetnih nota.', en: 'Premium dry white wine with unique floral aromatics and freshness.', sq: 'Verë e bardhë premium me freski të jashtëzakonshme i nota lulesh.' },
    price: 26.00,
    category: Category.WINES,
    image: '',
    allergens: [],
    dietary: [],
    calories: 510,
    prepTime: 1,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_roze_plantaze_large',
    name: { sr: 'Roze Plantaže 0.70l', en: 'Rose Plantaze 0.70l', sq: 'Rozë Plantaze 0.70l' },
    description: { sr: 'Sveže crnogorsko roze vino punjeno u flašu od 0.70l.', en: 'Refreshing Montenegrin premium rose wine (0.70l).', sq: 'Verë rozë premium e freskët e Malit të Zi (0.70l).' },
    price: 18.00,
    category: Category.WINES,
    image: '',
    allergens: [],
    dietary: [],
    calories: 500,
    prepTime: 1,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },

  // --- COCKTAILS (Kokteli) ---
  {
    id: 'drk_gin_tonic',
    name: { sr: 'Gin-Tonic 0.02l', en: 'Gin Tonic 0.02l', sq: 'Xhin Tonik 0.02l' },
    description: { sr: 'Prefinjeni džin sa osvežavajućim tonikom, ledom i limunom.', en: 'Classic crisp gin combined with tonic water, ice and fresh lemon.', sq: 'Xhin klasik i kombinuar me tonik, akull i limon të freskët.' },
    price: 5.00,
    category: Category.COCKTAILS,
    image: '',
    allergens: [],
    dietary: [],
    calories: 120,
    prepTime: 2,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_campari_soda',
    name: { sr: 'Campari-soda 0.02l', en: 'Campari Soda 0.02l', sq: 'Kampari Sodë 0.02l' },
    description: { sr: 'Gorko-slatki Campari pomešan sa gaziranom sodom i ledom.', en: 'Vibrant bittersweet Campari mixed with carbonated soda water and ice.', sq: 'Kampari i kuq i kombinuar me ujë me gaz i akull.' },
    price: 5.50,
    category: Category.COCKTAILS,
    image: '',
    allergens: [],
    dietary: [],
    calories: 110,
    prepTime: 2,
    featured: false,
    ingredients: { sr: [], en: [], sq: [] }
  },
  {
    id: 'drk_aperol_spritz',
    name: { sr: 'Aperol Spritz 0.03l', en: 'Aperol Spritz 0.03l', sq: 'Aperol Spric 0.03l' },
    description: { sr: 'Slavni Aperol sa penušavim Proseccom, sodom i narandžom.', en: 'Refreshing Aperol with sparkling Prosecco, soda, ice and a slice of orange.', sq: 'Aperol freskues me Prosecco të gazuar, sodë, akull i portokall.' },
    price: 7.00,
    category: Category.COCKTAILS,
    image: '',
    allergens: [],
    dietary: [],
    calories: 140,
    prepTime: 2,
    featured: true,
    ingredients: { sr: [], en: [], sq: [] }
  },
  
  // --- DESSERTS (Dezerti) ---
  {
    id: 'des_1',
    name: { sr: 'Slatke palačinke', en: 'Sweet Crepes', sq: 'Palaçinka të Ëmbla' },
    description: { sr: 'Domaće palačinke punjene Uno ladom, džemom ili medom.', en: 'Homemade crepes stuffed with Uno lada cream, jam, or honey.', sq: 'Palaçinka shtëpie të mbushure me Uno lada, reçel ose mjaltë.' },
    price: 4.00,
    category: Category.DESSERTS,
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=500&auto=format&fit=crop&q=80',
    allergens: ['gluten', 'dairy', 'egg'],
    dietary: ['veg'],
    calories: 410,
    prepTime: 8,
    featured: true,
    ingredients: { sr: ['Palačinke', 'Uno lada / džem / med'], en: ['Crepes', 'Uno lada / jam / honey'], sq: ['Palaçinka', 'Uno lada / reçel / mjaltë'] }
  },
  {
    id: 'des_2',
    name: { sr: 'Verde palačinke', en: 'Verde Pistachio Crepes', sq: 'Palaçinka Verde' },
    description: { sr: 'Domaće palačinke sa belim kremom, prelivom i seckanim pistaćima.', en: 'Crepes filled with white cream, topped with pistachio syrup and pistachios.', sq: 'Palaçinka shtëpie me krem të bardhë, salcë pistaqi dhe pistaqë.' },
    price: 6.80,
    category: Category.DESSERTS,
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=500&auto=format&fit=crop&q=80',
    allergens: ['gluten', 'dairy', 'egg', 'nuts'],
    dietary: ['veg'],
    calories: 490,
    prepTime: 10,
    featured: true,
    ingredients: { sr: ['Palačinke', 'Beli krem', 'Preliv od pistaća', 'Pistaći'], en: ['Crepes', 'White cream', 'Pistachio glaze', 'Pistachios'], sq: ['Palaçinka', 'Krem i bardhë', 'Salcë pistaqi', 'Pistaqë'] }
  },
  {
    id: 'des_3',
    name: { sr: 'Kolač dana', en: 'Cake of the Day', sq: 'Ëmbëlsira e Ditës' },
    description: { sr: 'Svež domaći kolač dana po izboru našeg poslastičara.', en: 'Fresh artisan cake prepared daily. Ask about today’s specials.', sq: 'Ëmbëlsirë shtëpie e gatuar e freskët çdo ditë.' },
    price: 5.00,
    category: Category.DESSERTS,
    image: '/src/assets/images/chocolate_lava_cake_1784588896614.jpg',
    allergens: ['gluten', 'dairy', 'egg'],
    dietary: ['veg'],
    calories: 380,
    prepTime: 5,
    featured: false,
    ingredients: { sr: ['Domaći sastojci'], en: ['Homemade ingredients'], sq: ['Përbërës shtëpie'] }
  }
];

export interface MezeIngredient {
  id: string;
  name: Translation;
  weight: number; // in grams
  price: number; // in EUR
  calories: number;
  category: 'meat' | 'cheese' | 'sides';
  icon: string;
}

export const MEZE_INGREDIENTS: MezeIngredient[] = [
  {
    id: 'meze_prsut',
    name: { sr: 'Njeguški pršut', en: 'Njegusi Prosciutto', sq: 'Prshutë Njegushi' },
    weight: 50,
    price: 4.00,
    calories: 160,
    category: 'meat',
    icon: '🥓'
  },
  {
    id: 'meze_kulen',
    name: { sr: 'Domaći ljuti kulen', en: 'Local Spicy Salami', sq: 'Sallam shtëpie djegës' },
    weight: 50,
    price: 3.00,
    calories: 180,
    category: 'meat',
    icon: '🌶️'
  },
  {
    id: 'meze_sir_njegusi',
    name: { sr: 'Njeguški stari sir', en: 'Njegusi Aged Cheese', sq: 'Djathë Njegushi i vjetëruar' },
    weight: 50,
    price: 3.50,
    calories: 190,
    category: 'cheese',
    icon: '🧀'
  },
  {
    id: 'meze_sir_pljevlja',
    name: { sr: 'Pljevaljski sir u ulju', en: 'Pljevlja Cheese in Oil', sq: 'Djathë Pljevlja në vaj' },
    weight: 50,
    price: 2.80,
    calories: 145,
    category: 'cheese',
    icon: '🥣'
  },
  {
    id: 'meze_kajmak',
    name: { sr: 'Mladi slani kajmak', en: 'Fresh Kajmak Cream', sq: 'Kajmak i freskët' },
    weight: 40,
    price: 2.00,
    calories: 130,
    category: 'cheese',
    icon: '🧈'
  },
  {
    id: 'meze_masline',
    name: { sr: 'Marinirane masline', en: 'Marinated Olives', sq: 'Ullinj të marinuar' },
    weight: 30,
    price: 1.50,
    calories: 45,
    category: 'sides',
    icon: '🫒'
  },
  {
    id: 'meze_ustipci',
    name: { sr: 'Domaći prženi uštipci', en: 'Crispy Fried Fritters', sq: 'Petulla shtëpie' },
    weight: 80,
    price: 2.20,
    calories: 220,
    category: 'sides',
    icon: '🥯'
  },
  {
    id: 'meze_ajvar',
    name: { sr: 'Domaći blagi ajvar', en: 'Homemade Ajvar Relish', sq: 'Ajvar shtëpie' },
    weight: 40,
    price: 1.50,
    calories: 50,
    category: 'sides',
    icon: '🏺'
  }
];

export const REVIEWS: Review[] = [];

export const DIETARY_LABELS = {
  veg: {
    label: { sr: 'Vegetarijansko', en: 'Vegetarian', sq: 'Vegjetariane' },
    color: 'bg-green-50 text-green-700 border-green-200 dark:bg-green-950/40 dark:text-green-300 dark:border-green-900',
    icon: '🍃'
  },
  vegan: {
    label: { sr: 'Vegansko', en: 'Vegan', sq: 'Vegane' },
    color: 'bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950/40 dark:text-emerald-300 dark:border-emerald-900',
    icon: '🌱'
  },
  gf: {
    label: { sr: 'Bez glutena', en: 'Gluten-Free', sq: 'Pa Gluten' },
    color: 'bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950/40 dark:text-amber-300 dark:border-amber-900',
    icon: '🌾'
  },
  spicy: {
    label: { sr: 'Ljuto', en: 'Spicy', sq: 'Djegëse' },
    color: 'bg-red-50 text-red-700 border-red-200 dark:bg-red-950/40 dark:text-red-300 dark:border-red-900',
    icon: '🌶️'
  }
};

export const ALLERGENS_LABELS: Record<string, Translation> = {
  gluten: { sr: 'Gluten', en: 'Gluten', sq: 'Gluten' },
  dairy: { sr: 'Mlečni proizvodi', en: 'Dairy', sq: 'Laktik (Bulmet)' },
  nuts: { sr: 'Koštunjavo voće', en: 'Nuts', sq: 'Fruta Thata' },
  seafood: { sr: 'Plodovi mora', en: 'Seafood', sq: 'Fruta Deti' },
  egg: { sr: 'Jaja', en: 'Eggs', sq: 'Vezë' }
};

export const DICTIONARY = {
  restaurantName: { sr: 'Caffee&Food', en: 'Caffee&Food', sq: 'Caffee&Food' },
  tagline: { sr: 'Mediteranski ukusi & Tradicija', en: 'Mediterranean Flavors & Tradition', sq: 'Shije Mesdhetare & Traditë' },
  searchPlaceholder: { sr: 'Pretražite jela, sastojke...', en: 'Search dishes, ingredients...', sq: 'Kërko pjatat, përbërësit...' },
  allCategories: { sr: 'Sva jela', en: 'All Dishes', sq: 'Të gjitha' },
  breakfast: { sr: 'Doručak', en: 'Breakfast', sq: 'Mëngjes' },
  food: { sr: 'Hrana', en: 'Food', sq: 'Ushqim' },
  hot_drinks: { sr: 'Topli napici', en: 'Hot Drinks', sq: 'Pije të Ngrohta' },
  non_alcoholic: { sr: 'Sokovi i pića', en: 'Soft Drinks & Juices', sq: 'Lëngje & Pije' },
  beers: { sr: 'Piva', en: 'Beers', sq: 'Birra' },
  wines: { sr: 'Vina', en: 'Wines', sq: 'Vera' },
  alcohol: { sr: 'Žestoka pića', en: 'Spirits & Liqueurs', sq: 'Pije të Forta' },
  cocktails: { sr: 'Kokteli', en: 'Cocktails', sq: 'Kokteje' },
  starters: { sr: 'Predjela', en: 'Starters', sq: 'Paragjella' },
  mains: { sr: 'Glavna jela', en: 'Main Courses', sq: 'Gjellë Kryesore' },
  desserts: { sr: 'Dezerti', en: 'Desserts', sq: 'Ëmbëlsira' },
  drinks: { sr: 'Pića', en: 'Drinks', sq: 'Pije' },
  dietaryFilter: { sr: 'Filter ishrane', en: 'Dietary Filters', sq: 'Filtrat e Ushqimit' },
  sortBy: { sr: 'Sortiraj po', en: 'Sort by', sq: 'Rendit sipas' },
  priceAsc: { sr: 'Ceni: Od niže ka višoj', en: 'Price: Low to High', sq: 'Çmimi: Rritës' },
  priceDesc: { sr: 'Ceni: Od više ka nižoj', en: 'Price: High to Low', sq: 'Çmimi: Zbritës' },
  timeAsc: { sr: 'Vremenu pripreme', en: 'Preparation Time', sq: 'Koha e Përgatitjes' },
  caloriesAsc: { sr: 'Kalorijama', en: 'Calories', sq: 'Kaloritë' },
  allergens: { sr: 'Alergeni', en: 'Allergens', sq: 'Alergjenët' },
  ingredients: { sr: 'Sastojci', en: 'Ingredients', sq: 'Përbërësit' },
  prepTime: { sr: 'Vreme pripreme', en: 'Prep time', sq: 'Koha e përgatitjes' },
  calories: { sr: 'Kalorije', en: 'Calories', sq: 'Kalori' },
  addToOrder: { sr: 'Dodaj u porudžbinu', en: 'Add to Order', sq: 'Shto në Porosi' },
  myOrder: { sr: 'Moja porudžbina', en: 'My Order', sq: 'Porosia Ime' },
  emptyOrder: { sr: 'Vaša porudžbina je prazna.', en: 'Your order is currently empty.', sq: 'Porosia juaj është bosh.' },
  tableNumber: { sr: 'Broj stola', en: 'Table Number', sq: 'Numri i Tavolinës' },
  specialNotes: { sr: 'Posebne napomene (npr. bez luka)', en: 'Special instructions (e.g. no onions)', sq: 'Shënime të veçanta (p.sh. pa qepë)' },
  callWaiter: { sr: 'Pozovi konobara', en: 'Call Waiter', sq: 'Thirr Kamerierin' },
  placeOrder: { sr: 'Pošalji porudžbinu', en: 'Place Order', sq: 'Dërgo Porosinë' },
  waiterCalled: { sr: 'Konobar je pozvan! Stiže ubrzo do Vašeg stola.', en: 'Waiter has been summoned! Someone will be with you shortly.', sq: 'Kamerieri u thirr! Do të vijë së shpejti në tavolinën tuaj.' },
  orderSuccess: { sr: 'Porudžbina uspešno poslata kuhinji!', en: 'Order successfully sent to the kitchen!', sq: 'Porosia u dërgua me sukses në kuzhinë!' },
  orderEstimated: { sr: 'Procenjeno vreme pripreme', en: 'Estimated prep time', sq: 'Koha e vlerësuar' },
  leaveReview: { sr: 'Ostavite utisak', en: 'Leave a Review', sq: 'Lini një Vlerësim' },
  reviewName: { sr: 'Vaše ime', en: 'Your Name', sq: 'Emri Juaj' },
  reviewComment: { sr: 'Komentar', en: 'Comment', sq: 'Koment' },
  submitReview: { sr: 'Pošalji utisak', en: 'Submit Review', sq: 'Dërgo Vlerësimin' },
  guestReviews: { sr: 'Utisci naših gostiju', en: 'Guest Reviews', sq: 'Vlerësimet e Mysafirëve' },
  customMeze: { sr: 'Sastavite svoju mezu', en: 'Craft Your Custom Platter', sq: 'Krijoni Mezën tuaj' },
  mezeDesc: { sr: 'Izaberite lokalne delikatese i sami kreirajte savršenu dasku predjela.', en: 'Select local delicacies and design your custom charcuterie board.', sq: 'Zgjidhni delikatet lokale dhe krijoni pjatën tuaj të përsosur.' },
  totalWeight: { sr: 'Ukupna težina', en: 'Total Weight', sq: 'Pesha totale' },
  totalPrice: { sr: 'Ukupna cena', en: 'Total Price', sq: 'Çmimi total' },
  minutes: { sr: 'min', en: 'min', sq: 'min' },
  addMore: { sr: 'Dodaj još', en: 'Add More', sq: 'Shto më shumë' },
  resetMeze: { sr: 'Resetuj', en: 'Reset', sq: 'Rifillo' },
  addMezeToCart: { sr: 'Dodaj mezu u porudžbinu', en: 'Add Platter to Order', sq: 'Shto Mezën në Porosi' },
  customPlatterTitle: { sr: 'Moja Kreirana Meza', en: 'My Crafted Platter', sq: 'Meza ime e Krijuar' },
  orderNotes: { sr: 'Napomena', en: 'Note', sq: 'Shënim' },
  noAllergens: { sr: 'Nema poznatih alergena', en: 'No known allergens', sq: 'Nuk ka alergjenë të njohur' },
};
